local layer_z = { 0.16, 2.0, 3.0 } -- layer 1, layer 2, layer 3 with default z values

go.property("layer",1) -- exposes this value to be able to be changed in editor, defaults to 1

function update(self, dt)
	local pos = go.get_position()
	pos.z = layer_z[self.layer]-pos.y*0.0001 -- start with layer z default, modify it based on y position
	--print("y: " .. pos.y)
	--print("z: " .. pos.z)
	go.set_position(pos)
end